name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format check
        run: deno fmt --check

      - name: Deploy check
        run: |
          deno install -Afr --no-check https://deno.land/x/deploy/deployctl.ts
          deployctl check mod.ts

      - name: Run tests
        run: deno test --unstable --allow-all

      - name: Start application
        run: deno run --allow-net --allow-read mod.ts
